version: '3.8'

services:
  loadbalancer:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./clients.json:/app/clients.json:rw
    depends_on:
      - backend1
      - backend2
      - backend3
    environment:
      - CONFIG_PATH=/app/config.json

  backend1:
    image: alpine:latest
    command: sh -c "while true; do echo -e 'HTTP/1.1 200 OK\r\n\r\nResponse from backend 1' | nc -l -p 8081; done"
    ports:
      - "8081:8081"

  backend2:
    image: alpine:latest
    command: sh -c "while true; do echo -e 'HTTP/1.1 200 OK\r\n\r\nResponse from backend 2' | nc -l -p 8082; done"
    ports:
      - "8082:8082"

  backend3:
    image: alpine:latest
    command: sh -c "while true; do echo -e 'HTTP/1.1 200 OK\r\n\r\nResponse from backend 3' | nc -l -p 8083; done"
    ports:
      - "8083:8083"